"""20180102

Revision ID: 66e9b6f87d52
Revises: df2e53bd6bcc
Create Date: 2018-01-21 14:15:51.451889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66e9b6f87d52'
down_revision = 'df2e53bd6bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ih_user_profile', 'update_time')
    op.drop_column('ih_user_profile', 'create_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_user_profile', sa.Column('create_time', mysql.DATETIME(), nullable=True))
    op.add_column('ih_user_profile', sa.Column('update_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
