"""20180123

Revision ID: 769eb63ce8c3
Revises: c38cc6284c73
Create Date: 2018-01-21 21:51:30.209019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '769eb63ce8c3'
down_revision = 'c38cc6284c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cre_user_profile', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.drop_column('cre_user_profile', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cre_user_profile', sa.Column('password', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('cre_user_profile', 'password_hash')
    # ### end Alembic commands ###
