"""20180122

Revision ID: c38cc6284c73
Revises: 1ab76f14a7d3
Create Date: 2018-01-21 20:29:16.007940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c38cc6284c73'
down_revision = '1ab76f14a7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cre_user_profile', sa.Column('password', sa.String(length=128), nullable=False))
    op.add_column('cre_user_profile', sa.Column('username', sa.String(length=32), nullable=False))
    op.drop_index('use_name', table_name='cre_user_profile')
    op.create_unique_constraint(None, 'cre_user_profile', ['username'])
    op.drop_column('cre_user_profile', 'use_name')
    op.drop_column('cre_user_profile', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cre_user_profile', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('cre_user_profile', sa.Column('use_name', mysql.VARCHAR(length=32), nullable=False))
    op.drop_constraint(None, 'cre_user_profile', type_='unique')
    op.create_index('use_name', 'cre_user_profile', ['use_name'], unique=True)
    op.drop_column('cre_user_profile', 'username')
    op.drop_column('cre_user_profile', 'password')
    # ### end Alembic commands ###
